[package]
name = "yew-cart"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3"
web-sys = "0.3"
yew = { version = "0.20.0", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.33"